frete gratis e lojas Mlivre
rafaelcruzpb/Impressora3DBrasil pull request #22
Opened 2020-01-18 18:14 UTC by hern4ndes

adição do campo se as lojas fornecem frete grátis  ou não e o link da lojas no mercado livre(aproveitar o frete grátis acima de 120 reais )

2020-01-19 20:28 UTC, rafaelcruzpb requested changes

2020-01-19 20:28 UTC, rafaelcruzpb commented on README.md
> +	<td><a href="https://www.mercadolivre.com.br/perfil/3D+LAB">3D Lab Mercado Livre</a></td>
@hern4ndes esse link não tá sendo exibido da forma correta, quebrou o markdown nessa coluna, dá uma olhada nisso.

2020-01-23 22:19 UTC, hern4ndes commented on README.md
> +	<td><a href="https://www.mercadolivre.com.br/perfil/3D+LAB">3D Lab Mercado Livre</a></td>
Resolvido, abrindo um novo PR com a correção

2020-01-23 22:21 UTC, hern4ndes commented
corrigido

2020-01-23 22:24 UTC, hern4ndes commented
fechei o pr sem querer

2020-01-24 04:42 UTC, merged